export const countrys = [
  {
    country: "Afghanistan",
    flag_icon: "af",
  },
  {
    country: "Albania",
    flag_icon: "al",
  },
  {
    country: "Algeria",
    flag_icon: "dz",
  },
  {
    country: "Andorra",
    flag_icon: "ad",
  },
  {
    country: "Angola",
    flag_icon: "ao",
  },
  {
    country: "Argentina",
    flag_icon: "ar",
  },
  {
    country: "Armenia",
    flag_icon: "am",
  },
  {
    country: "Australia",
    flag_icon: "au",
  },
  {
    country: "Austria",
    flag_icon: "at",
  },
  {
    country: "Azerbaijan",
    flag_icon: "az",
  },
  {
    country: "Bahamas",
    flag_icon: "bs",
  },
  {
    country: "Bahrain",
    flag_icon: "bh",
  },
  {
    country: "Bangladesh",
    flag_icon: "bd",
  },
  {
    country: "Barbados",
    flag_icon: "bb",
  },
  {
    country: "Belarus",
    flag_icon: "by",
  },
  {
    country: "Belgium",
    flag_icon: "be",
  },
  {
    country: "Belize",
    flag_icon: "bz",
  },
  {
    country: "Benin",
    flag_icon: "bj",
  },
  {
    country: "Bhutan",
    flag_icon: "bt",
  },
  {
    country: "Bolivia",
    flag_icon: "bo",
  },
  {
    country: "Bosnia and Herzegovina",
    flag_icon: "ba",
  },
  {
    country: "Botswana",
    flag_icon: "bw",
  },
  {
    country: "Brazil",
    flag_icon: "br",
  },
  {
    country: "Brunei",
    flag_icon: "bn",
  },
  {
    country: "Bulgaria",
    flag_icon: "bg",
  },
  {
    country: "Burkina Faso",
    flag_icon: "bf",
  },
  {
    country: "Burundi",
    flag_icon: "bi",
  },
  {
    country: "Cabo Verde",
    flag_icon: "cv",
  },
  {
    country: "Cambodia",
    flag_icon: "kh",
  },
  {
    country: "Cameroon",
    flag_icon: "cm",
  },
  {
    country: "Canada",
    flag_icon: "ca",
  },
  {
    country: "Central African Republic",
    flag_icon: "cf",
  },
  {
    country: "Chad",
    flag_icon: "td",
  },
  {
    country: "Chile",
    flag_icon: "cl",
  },
  {
    country: "China",
    flag_icon: "cn",
  },
  {
    country: "Colombia",
    flag_icon: "co",
  },
  {
    country: "Comoros",
    flag_icon: "km",
  },
  {
    country: "Congo",
    flag_icon: "cg",
  },
  {
    country: "Costa Rica",
    flag_icon: "cr",
  },
  {
    country: "Croatia",
    flag_icon: "hr",
  },
  {
    country: "Cuba",
    flag_icon: "cu",
  },
  {
    country: "Cyprus",
    flag_icon: "cy",
  },
  {
    country: "Czech Republic",
    flag_icon: "cz",
  },
  {
    country: "Democratic Republic of the Congo",
    flag_icon: "cd",
  },
  {
    country: "Denmark",
    flag_icon: "dk",
  },
  {
    country: "Djibouti",
    flag_icon: "dj",
  },
  {
    country: "Dominica",
    flag_icon: "dm",
  },
  {
    country: "Dominican Republic",
    flag_icon: "do",
  },
  {
    country: "Ecuador",
    flag_icon: "ec",
  },
  {
    country: "Egypt",
    flag_icon: "eg",
  },
  {
    country: "El Salvador",
    flag_icon: "sv",
  },
  {
    country: "Equatorial Guinea",
    flag_icon: "gq",
  },
  {
    country: "Eritrea",
    flag_icon: "er",
  },
  {
    country: "Estonia",
    flag_icon: "ee",
  },
  {
    country: "Eswatini",
    flag_icon: "sz",
  },
  {
    country: "Ethiopia",
    flag_icon: "et",
  },
  {
    country: "Fiji",
    flag_icon: "fj",
  },
  {
    country: "Finland",
    flag_icon: "fi",
  },
  {
    country: "France",
    flag_icon: "fr",
  },
  {
    country: "Gabon",
    flag_icon: "ga",
  },
  {
    country: "Gambia",
    flag_icon: "gm",
  },
  {
    country: "Georgia",
    flag_icon: "ge",
  },
  {
    country: "Germany",
    flag_icon: "de",
  },
  {
    country: "Ghana",
    flag_icon: "gh",
  },
  {
    country: "Greece",
    flag_icon: "gr",
  },
  {
    country: "Grenada",
    flag_icon: "gd",
  },
  {
    country: "Guatemala",
    flag_icon: "gt",
  },
  {
    country: "Guinea",
    flag_icon: "gn",
  },
  {
    country: "Guinea-Bissau",
    flag_icon: "gw",
  },
  {
    country: "Guyana",
    flag_icon: "gy",
  },
  {
    country: "Haiti",
    flag_icon: "ht",
  },
  {
    country: "Honduras",
    flag_icon: "hn",
  },
  {
    country: "Hungary",
    flag_icon: "hu",
  },
  {
    country: "Iceland",
    flag_icon: "is",
  },
  {
    country: "India",
    flag_icon: "in",
  },
  {
    country: "Indonesia",
    flag_icon: "id",
  },
  {
    country: "Iran",
    flag_icon: "ir",
  },
  {
    country: "Iraq",
    flag_icon: "iq",
  },
  {
    country: "Ireland",
    flag_icon: "ie",
  },
  {
    country: "Israel",
    flag_icon: "il",
  },
  {
    country: "Italy",
    flag_icon: "it",
  },
  {
    country: "Jamaica",
    flag_icon: "jm",
  },
  {
    country: "Japan",
    flag_icon: "jp",
  },
  {
    country: "Jordan",
    flag_icon: "jo",
  },
  {
    country: "Kazakhstan",
    flag_icon: "kz",
  },
  {
    country: "Kenya",
    flag_icon: "ke",
  },
  {
    country: "Kiribati",
    flag_icon: "ki",
  },
  {
    country: "Kuwait",
    flag_icon: "kw",
  },
  {
    country: "Kyrgyzstan",
    flag_icon: "kg",
  },
  {
    country: "Laos",
    flag_icon: "la",
  },
  {
    country: "Latvia",
    flag_icon: "lv",
  },
  {
    country: "Lebanon",
    flag_icon: "lb",
  },
  {
    country: "Lesotho",
    flag_icon: "ls",
  },
  {
    country: "Liberia",
    flag_icon: "lr",
  },
  {
    country: "Libya",
    flag_icon: "ly",
  },
  {
    country: "Liechtenstein",
    flag_icon: "li",
  },
  {
    country: "Lithuania",
    flag_icon: "lt",
  },
  {
    country: "Luxembourg",
    flag_icon: "lu",
  },
  {
    country: "Madagascar",
    flag_icon: "mg",
  },
];

export const domasticLeads = [
  {
    flag: "in",
    country: "India",
    product: "Footwear",
    price: 4757,
    date: "2024-08",
  },
  {
    flag: "in",
    country: "India",
    product: "Groceries",
    price: 2918,
    date: "2024-03",
  },
  {
    flag: "in",
    country: "India",
    product: "Books",
    price: 1397,
    date: "2024-11",
  },
  {
    flag: "in",
    country: "India",
    product: "Furniture",
    price: 12860,
    date: "2024-04",
  },
  {
    flag: "in",
    country: "India",
    product: "Jewelry",
    price: 32480,
    date: "2024-01",
  },
  {
    flag: "in",
    country: "India",
    product: "Beauty Products",
    price: 475,
    date: "2024-02",
  },
  {
    flag: "in",
    country: "India",
    product: "Home Decor",
    price: 7893,
    date: "2024-10",
  },
  {
    flag: "in",
    country: "India",
    product: "Electronics",
    price: 29500,
    date: "2024-05",
  },
  {
    flag: "in",
    country: "India",
    product: "Apparel",
    price: 1998,
    date: "2024-07",
  },
  {
    flag: "in",
    country: "India",
    product: "Tools",
    price: 3847,
    date: "2024-06",
  },
  {
    flag: "in",
    country: "India",
    product: "Sports Equipment",
    price: 7425,
    date: "2024-09",
  },
  {
    flag: "in",
    country: "India",
    product: "Stationery",
    price: 250,
    date: "2024-12",
  },
  {
    flag: "in",
    country: "India",
    product: "Garden Supplies",
    price: 1899,
    date: "2024-03",
  },
  {
    flag: "in",
    country: "India",
    product: "Automobiles",
    price: 48200,
    date: "2024-04",
  },
  {
    flag: "in",
    country: "India",
    product: "Toys",
    price: 1290,
    date: "2024-01",
  },
  {
    flag: "in",
    country: "India",
    product: "Footwear",
    price: 2100,
    date: "2024-08",
  },
  {
    flag: "in",
    country: "India",
    product: "Books",
    price: 1450,
    date: "2024-02",
  },
  {
    flag: "in",
    country: "India",
    product: "Furniture",
    price: 13500,
    date: "2024-10",
  },
  {
    flag: "in",
    country: "India",
    product: "Jewelry",
    price: 32000,
    date: "2024-06",
  },
  {
    flag: "in",
    country: "India",
    product: "Beauty Products",
    price: 650,
    date: "2024-11",
  },
  {
    flag: "in",
    country: "India",
    product: "Home Decor",
    price: 8250,
    date: "2024-07",
  },
  {
    flag: "in",
    country: "India",
    product: "Electronics",
    price: 30500,
    date: "2024-09",
  },
  {
    flag: "in",
    country: "India",
    product: "Apparel",
    price: 1800,
    date: "2024-05",
  },
  {
    flag: "in",
    country: "India",
    product: "Tools",
    price: 4100,
    date: "2024-12",
  },
  {
    flag: "in",
    country: "India",
    product: "Sports Equipment",
    price: 7800,
    date: "2024-04",
  },
  {
    flag: "in",
    country: "India",
    product: "Stationery",
    price: 300,
    date: "2024-03",
  },
  {
    flag: "in",
    country: "India",
    product: "Garden Supplies",
    price: 2000,
    date: "2024-01",
  },
  {
    flag: "in",
    country: "India",
    product: "Automobiles",
    price: 49000,
    date: "2024-02",
  },
  {
    flag: "in",
    country: "India",
    product: "Toys",
    price: 1390,
    date: "2024-11",
  },
  {
    flag: "in",
    country: "India",
    product: "Footwear",
    price: 2250,
    date: "2024-08",
  },
  {
    flag: "in",
    country: "India",
    product: "Sports Equipment",
    price: 7925,
    date: "2024-07",
  },
  {
    flag: "in",
    country: "India",
    product: "Stationery",
    price: 275,
    date: "2024-12",
  },
  {
    flag: "in",
    country: "India",
    product: "Garden Supplies",
    price: 1950,
    date: "2024-05",
  },
  {
    flag: "in",
    country: "India",
    product: "Automobiles",
    price: 48800,
    date: "2024-09",
  },
  {
    flag: "in",
    country: "India",
    product: "Toys",
    price: 1335,
    date: "2024-01",
  },
];

export const interNationLeads = [
  {
    flag: "us",
    country: "United States",
    product: "Electronics",
    price: 29000,
    date: "2024-07",
  },
  {
    flag: "gb",
    country: "United Kingdom",
    product: "Apparel",
    price: 1500,
    date: "2024-03",
  },
  {
    flag: "ca",
    country: "Canada",
    product: "Furniture",
    price: 12500,
    date: "2024-08",
  },
  {
    flag: "de",
    country: "Germany",
    product: "Automobiles",
    price: 48000,
    date: "2024-12",
  },
  {
    flag: "jp",
    country: "Japan",
    product: "Toys",
    price: 1300,
    date: "2024-04",
  },
  {
    flag: "fr",
    country: "France",
    product: "Beauty Products",
    price: 600,
    date: "2024-11",
  },
  {
    flag: "au",
    country: "Australia",
    product: "Sports Equipment",
    price: 7500,
    date: "2024-02",
  },
  {
    flag: "it",
    country: "Italy",
    product: "Jewelry",
    price: 32000,
    date: "2024-06",
  },
  {
    flag: "br",
    country: "Brazil",
    product: "Groceries",
    price: 2900,
    date: "2024-10",
  },
  {
    flag: "ru",
    country: "Russia",
    product: "Footwear",
    price: 2000,
    date: "2024-01",
  },
  {
    flag: "cn",
    country: "China",
    product: "Electronics",
    price: 31000,
    date: "2024-05",
  },
  {
    flag: "es",
    country: "Spain",
    product: "Home Decor",
    price: 8000,
    date: "2024-09",
  },
  {
    flag: "mx",
    country: "Mexico",
    product: "Tools",
    price: 4000,
    date: "2024-04",
  },
  {
    flag: "za",
    country: "South Africa",
    product: "Books",
    price: 1400,
    date: "2024-07",
  },
  {
    flag: "kr",
    country: "South Korea",
    product: "Stationery",
    price: 300,
    date: "2024-03",
  },
  {
    flag: "in",
    country: "India",
    product: "Furniture",
    price: 13000,
    date: "2024-08",
  },
  {
    flag: "ae",
    country: "United Arab Emirates",
    product: "Jewelry",
    price: 35000,
    date: "2024-01",
  },
  {
    flag: "nz",
    country: "New Zealand",
    product: "Beauty Products",
    price: 550,
    date: "2024-11",
  },
  {
    flag: "se",
    country: "Sweden",
    product: "Garden Supplies",
    price: 2000,
    date: "2024-02",
  },
  {
    flag: "sa",
    country: "Saudi Arabia",
    product: "Automobiles",
    price: 47000,
    date: "2024-06",
  },
  {
    flag: "sg",
    country: "Singapore",
    product: "Toys",
    price: 1250,
    date: "2024-12",
  },
  {
    flag: "ch",
    country: "Switzerland",
    product: "Apparel",
    price: 1700,
    date: "2024-04",
  },
  {
    flag: "ar",
    country: "Argentina",
    product: "Groceries",
    price: 2850,
    date: "2024-10",
  },
  {
    flag: "ke",
    country: "Kenya",
    product: "Footwear",
    price: 1800,
    date: "2024-03",
  },
  {
    flag: "pl",
    country: "Poland",
    product: "Home Decor",
    price: 7900,
    date: "2024-05",
  },
  {
    flag: "tr",
    country: "Turkey",
    product: "Electronics",
    price: 29500,
    date: "2024-09",
  },
  {
    flag: "eg",
    country: "Egypt",
    product: "Sports Equipment",
    price: 7600,
    date: "2024-07",
  },
  {
    flag: "no",
    country: "Norway",
    product: "Tools",
    price: 4100,
    date: "2024-08",
  },
  {
    flag: "il",
    country: "Israel",
    product: "Books",
    price: 1500,
    date: "2024-06",
  },
  {
    flag: "fi",
    country: "Finland",
    product: "Stationery",
    price: 350,
    date: "2024-11",
  },
  {
    flag: "gr",
    country: "Greece",
    product: "Home Decor",
    price: 8100,
    date: "2024-10",
  },
  {
    flag: "dk",
    country: "Denmark",
    product: "Apparel",
    price: 1900,
    date: "2024-01",
  },
  {
    flag: "id",
    country: "Indonesia",
    product: "Electronics",
    price: 30000,
    date: "2024-09",
  },
  {
    flag: "pt",
    country: "Portugal",
    product: "Furniture",
    price: 12750,
    date: "2024-04",
  },
  {
    flag: "my",
    country: "Malaysia",
    product: "Beauty Products",
    price: 650,
    date: "2024-05",
  },
  {
    flag: "ua",
    country: "Ukraine",
    product: "Automobiles",
    price: 48000,
    date: "2024-12",
  },
  {
    flag: "th",
    country: "Thailand",
    product: "Jewelry",
    price: 33000,
    date: "2024-03",
  },
];
